### ISSUE TITLE
When i search for an artist then go to "featured" section, some of the featured playlists keep loading

### ISSUE THREAD

**Issue by dainvincible1** [fast4x/RiMusic#111]
### Steps to reproduce the bug

Search "Taylor swift" then go to "featured". then you'll find few playlists. some of them will not open, they keep loading 

### Expected behavior

featured playlists should open

### Actual behavior

featured playlists doesnt open

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/127825700/71a64558-7c06-48eb-be1b-5e321170089d

### RiMusic version

0.6.8

### Android version

android 11

**Comment by ikanakova** [comment]
I think there must be some bug in the playlist, because the Presenting the Weeknd and Emotional Pop Songs for the Sunset one normally works for me, but the Ultimate '90s Party songs don't load either.

**Comment by dainvincible1** [comment]
> I think there must be some bug in the playlist, because the Presenting the Weeknd and Emotional Pop Songs for the Sunset one normally works for me, but the Ultimate '90s Party songs don't load either.

one thing i noticed...if you turn off your internet then the playlist loads. but then if you go back and turn internet on then playlist doesnt load anymore

https://github.com/fast4x/RiMusic/assets/127825700/0af692b6-0a69-4f5c-bee9-fdeec8263ff0

**Comment by ikanakova** [comment]
YouTube Music playlist link: https://music.youtube.com/playlist?list=RDCLAK5uy_nvu_HUY0DPNpbB_V0moUfs9s5zABAF8xQ&playnext=1&si=08l4qhEQMQQ0Wl_8

**Comment by dainvincible1** [comment]
> YouTube Music playlist link: https://music.youtube.com/playlist?list=RDCLAK5uy_nvu_HUY0DPNpbB_V0moUfs9s5zABAF8xQ&playnext=1&si=08l4qhEQMQQ0Wl_8

The link opens in yt music and harmony music

**Comment by fast4x** [comment]
Ok, i'll check it

**Comment by 25huizengek1** [comment]
I happen to have encountered this issue with my own fork of ViMusic too. This is because the PlaylistSongList doesn't really handle pagination and calls `completed` (util function). `completed` searches for all songs in a playlist, but YouTube sometimes has weird inconsistencies or 'infinite' playlists, so it could occur that this function just never returns, resulting in infinite load time. As a quick fix I added a `maxDepth` parameter to this function to account for this. I do not know whether this is the best solution, but I guess this works for now. 

https://github.com/25huizengek1/ViMusic/blob/2e18de149455b6ad1ff9e1d70d389a5e6ee019d5/app/src/main/kotlin/it/vfsfitvnm/vimusic/utils/Utils.kt#L110
