### ISSUE TITLE
Otro bug donde se cierra la app.

### ISSUE THREAD

**Issue by Isav08** [fast4x/RiMusic#1127]
### Steps to reproduce the bug

1-Diregirse a listas de reproducciones publicas.
2-Ingresar a cualquiera.
3-Crear una lista personalizada.

### Expected behavior

Esto sucede en cualquier nueva lista.

### Actual behavior

Bug persistente.

### Screenshots/Screen recordings

![IMG_20240318_192217](https://github.com/fast4x/RiMusic/assets/163780688/a95f58af-5abd-4872-848d-d6d14e84cca0)
![IMG_20240318_192317](https://github.com/fast4x/RiMusic/assets/163780688/2603e7db-307a-4659-8034-a08c10e5e1c6)
![IMG_20240318_192347](https://github.com/fast4x/RiMusic/assets/163780688/0ba7500a-ed34-4002-989b-13546aa9593a)
![IMG_20240318_192417](https://github.com/fast4x/RiMusic/assets/163780688/73a30ca1-3b06-4226-b042-e0010bb10634)
![Screenshot_20240318-192022](https://github.com/fast4x/RiMusic/assets/163780688/6f5bd815-89e0-469e-bef6-7b87112be9ef)

### RiMusic version

0.6.26.1

### Android version

Android 7.0

### Additional information

En las ultimas horas que eh usado rimusic note algunos bug, pero estos son los únicos en donde la app se cierra.

**Comment by JZITNIK-github** [comment]
Lo siento, pero no tengo un teléfono con Android 7 en el que pueda probar este error. Sería realmente bueno si pudieras proporcionar algunos registros. Puedes usar alguna aplicación como `SysLog` para capturar logcat. ¿Este error comenzó con la última actualización o apareció antes?

PS for @fast4x : I don't think that the problem is with the commit where I used the MediaStora.Audio.Media.TITLE because as my last knowledge this property was there way before Android 7. So without logs I can't do much because I don't have Android 7 phone.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.27
