### ISSUE TITLE
[Feature]: Dual lyrics translation

### ISSUE THREAD

**Issue by magicpower-brother** [fast4x/RiMusic#1357]
### Description

Now you can't manually scroll on the lyrics page, and when translating lyrics, the original language display cannot be retained.

### Suggested Solution

Add dual-language display for lyrics, restore manual scrolling on the lyrics page.

**Comment by magicpower-brother** [comment]
It refers to manually scrolling lyrics under synchronized lyrics.

**Comment by fast4x** [comment]
Restored manual scroll, available from version 0.6.29

**Comment by Learner00100** [comment]
@fast4x 
Dual language lyrics display is nice concept.
We can make native language in bold, and translation of that line below without bold.
Also making current line synced lyrics as focused and remaining as faded.
This is concept UI is already present in musixmatch app.
And simpmusic also implemented it.
![Screenshot_2024-04-04-12-25-59-770_com maxrave simpmusic](https://github.com/fast4x/RiMusic/assets/102498820/0edc36e4-fcac-41dc-a9dd-a668ffddd298)


Since we not depend on translation from musixmatch, and we have instant translation from any lyrics to English.
We can follow above concept for implementation.
If pressed translate toggle is clicked , it should display translated lyrics (in different colour) bellow the each line of orginal lyrics.

**Comment by Learner00100** [comment]
Give can give customized option in settings like.
Click on translate icon toggle gives.
1. Translate only
2. Dual language.

Also copy lyrics option don't show up translated lyrics,
Kindly implement that also. Like
1.if no translate option clicked, copy lyrics option give original language alone.
2. translate option clicked, copy lyrics option give translation lyrics alone.
3. if dual Lang translate option clicked, copy lyrics option give original language with translation below each line.

**Comment by fast4x** [comment]
It is a series of features that require time

**Comment by Yuvaraj000dev** [comment]
> It is a series of features that require time

Any updates on the above ideas?

**Comment by fast4x** [comment]
@3359
