### ISSUE TITLE
Statistics are completely wrong

### ISSUE THREAD

**Issue by Abhishekahhi-io** [fast4x/RiMusic#1527]
### Steps to reproduce the bug

Statistics area

### Expected behavior

Show the actual statistics

### Actual behavior

It shows only recently played sessions not most played

### Logs

Fix it

### RiMusic version

0.6.30

### Android version

Android 12

**Comment by dAtA-TRoN** [comment]
This is because there is currently no song #1406

**Comment by dAtA-TRoN** [comment]
This is because there is currently no song #1406

**Comment by fast4x** [comment]
Explain to me how it should work for you, thank you.

**Comment by dAtA-TRoN** [comment]
> Explain to me how it should work for you, thank you.

Who exactly do you mean? Me or Abhishekahhi-io?

**Comment by fast4x** [comment]
both

**Comment by dAtA-TRoN** [comment]
> both

Well, actually, you just need to build this system that operates in the background without the user noticing. Additionally, you should add a feature to the settings where users can adjust the song listening threshold according to their preferences, with options such as one-quarter of the song, halfway through the song, or three-quarters into the song. It's crucial for users to have this flexibility because everyone has their own idea of where such a threshold should be. Once this system is in place, we could consider adding a fixed, low threshold for the history section, so not every song ends up there just because it was skipped briefly. Maybe around 10 seconds or so, or perhaps using percentages would be more appropriate. That makes more sense since sometimes there are very short songs, like skits or intros, where 10 seconds might already be too long. That's roughly how I envision it. Do you have any questions about this? Feel free to ask for clarification on why these features are necessary or anything else.

**Comment by fast4x** [comment]
There is...
![Screenshot_2024-04-15-13-44-07-397_it.fast4x.rimusic-edit.jpg](https://github.com/fast4x/RiMusic/assets/1484476/6c5175ac-cb1f-424d-a5a9-c5fbf2ec495b)

**Comment by dAtA-TRoN** [comment]
> There is...

OMG, it appears I've overlooked that until now. Could you please verify how this feature is implemented? Specifically, the details I conveyed regarding the images are essential for its functionality. Also, how does the feature integrate with statistics and the new history? It seems the statistics might not be accessing the necessary threshold, correct? And as previously mentioned, history requires its own, lower threshold.

**Comment by fast4x** [comment]
The threshold serves to increase the listening time of the song in time. If the user listens to a song, after crossing the threshold, the time spent listening to the song is saved.
The stats show the songs, playlists etc, which you’ve listened to the most over time.
History is simply a chronological list of the songs heard

**Comment by dAtA-TRoN** [comment]
Then it's already quite similar to what I suggested. However, my idea was that the threshold isn't tied to time. Because this way, one could theoretically reach the threshold of, let's say, 20 seconds, even if they listen to the first 10 seconds of a track twice because they really like the intro but aren't as interested in the rest of the track. In my idea, the actually listened portions of a song would matter. This means with a threshold of 20 seconds, you would need to have listened to 20 different seconds of the song for the statistical relevance to kick in. I think that's more accurate, but it's also much more complex to program. It's kind of you to explain the different areas (Stats, Playlist & History) to me again, but that's not what I meant. I don't know if you programmed the current implementation of the threshold yourself or if it was already in the app when you took it over. That's why I wanted you to take another close look to see if the current implementation actually affects the different areas as it should. Because there are obviously problems with the history. It seems to take over songs too quickly.

**Comment by fast4x** [comment]
No there is not in ViMusic, I implemented it later. If the time management is incorrect, it is understood well how to behave and development. I’ll look into it myself.

**Comment by dAtA-TRoN** [comment]
> No there is not in ViMusic, I implemented it later. If the time management is incorrect, it is understood well how to behave and development. I’ll look into it myself.

Nice. I'd appreciate it if you could provide me with an update on this matter as it piques my interest.

**Comment by fast4x** [comment]
Don’t call me her... call me your... :)

**Comment by dAtA-TRoN** [comment]
> Don’t call me her... call me your... :)

...what do you mean by that 🤔!?

**Comment by fast4x** [comment]
Nothing, it’s an Italian saying

**Comment by dAtA-TRoN** [comment]
> Nothing, it’s an Italian saying

Mamma Mia, I see.

**Comment by Lukilei** [comment]
Ciao! I also have this issue, the statistics just show the last played songs. Even if I select last month it just shows something I heard today or yesterday. Even though I have set the tips to be made by most played song.
