### ISSUE TITLE
Have the bar all the way down.

### ISSUE THREAD

**Issue by JeePopuwu** [fast4x/RiMusic#1567]
### Description

As we already know, Rimusic has multiple customization options for its style, one of which is placing the toolbar at the bottom of the screen, but I feel it could be better.

### Suggested Solution

The solution I suggest is to switch it up so that the music is at the bottom and the toolbar is at the top.
![Picsart_24-04-19_19-26-14-992](https://github.com/fast4x/RiMusic/assets/159836335/c1125708-30c3-42b0-89ab-0eea5bd95b40)
Something like what Spotify has in its interface.
![Screenshot_2024-04-19-19-21-21-455_com spotify music](https://github.com/fast4x/RiMusic/assets/159836335/09a64ee5-8609-4a79-91c1-e142004d252b)

### Additional Context

I think many people would prefer this layout. Thank you in advance for updating the application every week.

**Comment by dAtA-TRoN** [comment]
That has already been demanded multiple times, so it's a duplicate. According to Daniel, it's currently not possible to change this easily. But it will probably happen at some point. I would also appreciate it if this could happen sooner rather than later, as it's currently confusing and disruptive that the navigation bar (for those who display it at the bottom of the screen) jumps back and forth when listening to music. But we'll have to be patient about it.

**Comment by fast4x** [comment]
Daniel?

**Comment by dAtA-TRoN** [comment]
> Daniel?

![proxy-image(1).gif](https://github.com/fast4x/RiMusic/assets/71184627/44f50d0d-31b5-4d20-940e-eb45bb8c77c0)

Well, it had to happen eventually. So, since I run everything through ChatGPT that I say here, I needed an alias name for you, because 'fast4x' is often understood as a kind of function in translation, rather than a username. So far, I've always managed to delete this placeholder name before posting here. Not this time. Sorry, my bad Daniel 😂.

**Comment by dAtA-TRoN** [comment]
> You rely too much on chatgpt…

Okay, Father 😔.

**Comment by NightFly88** [comment]
We now know who you are Daniel, 🤣🤣🤣🤣

**Comment by NightFly88** [comment]
we know who you are daniel 🤣🤣🤣🤣

**Comment by fast4x** [comment]
> > You rely too much on chatgpt…
> 
> Okay, Father 😔.

Quite, use all you kike it

**Comment by aneesh1122** [comment]
Close this @fast4x or @JeePopuwu
