### ISSUE TITLE
Ability to remove song from playlist 

### ISSUE THREAD

**Issue by abdulkarimx1** [fast4x/RiMusic#1785]
### Description

The user cannot remove a song ( currently playing ) from playlist unless he exits the player and minimize it, and then removing the song from the list

### Suggested Solution

Adding a button to be able to remove the song while already being in the song 

### Additional Context

![Screenshot_20240505-171508_RiMusic](https://github.com/fast4x/RiMusic/assets/105733146/01fdb115-d8d9-49b1-81ba-234ac4c3f965)
![Screenshot_20240505-171931_RiMusic](https://github.com/fast4x/RiMusic/assets/105733146/8e870801-1bc0-4a28-9cc2-4aba077ffafc)

**Comment by AquamarineDreams** [comment]
That's probably because the queue may contain songs from other playlists. So, when opening a song menu, directly of the music player, the queue would need to know where that song came from, in order to delete it from your playlist.

Let's imagine the following situation:
You open your playlist like normal and, let's suppose, you have _back in black_ in it. After hearing _back in black_, you add it to your queue again, but, you add it from the music search. When listening to the song again, you decide to remove it from your playlist. You Open the song menu, and you wouldn't be able to, because the song you added isn't from your playlist.

In my opinion that would clutter the app with a unnecessary feature, that would possibly lead to users confusion.

**Comment by AquamarineDreams** [comment]
Remembering that this is my opinion, and fast4x is the one who decides whether or not to add it.
