### ISSUE TITLE
[Feature]: Download songs with lyrics

### ISSUE THREAD

**Issue by oliver-xie666** [fast4x/RiMusic#1861]
### Description

please i want Download songs with lyrics

### Suggested Solution

no lyrics download

**Comment by JeePopuwu** [comment]
It’s clear that you’re new. That feature is already in the app; you just need to enable "touch the cover," and the lyrics will appear there.
![Screenshot_2024-05-13-22-49-35-190_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/2a7cc4df-b5c1-4df9-85de-8e3db1455e9c)

**Comment by aneesh1122** [comment]
> It’s clear that you’re new. That feature is already in the app; you just need to enable "touch the cover," and the lyrics will appear there.
> ![Screenshot_2024-05-13-22-49-35-190_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/159836335/2a7cc4df-b5c1-4df9-85de-8e3db1455e9c)
> 

Well, he wants to download lyrics too. RiMusic caches those lyrics after you tap the cover.

You don't 'download' them, you cache them

**Comment by AquamarineDreams** [comment]
> Well, he wants to download lyrics too. RiMusic caches those lyrics after you tap the cover.
> 
> You don't 'download' them, you cache them

I'm pretty sure Rimusic doesn't cache lyrics. I think that it stores lyrics together with the database, so unless you delete your database, your lyrics will remain downloaded.

I say that because I have already deleted the app, and, when restoring my database, my custom lyrics reappeared.

https://github.com/fast4x/RiMusic/assets/140275860/a919af56-1fde-407b-8bda-32afbbf089c8

**Comment by fast4x** [comment]
try to resync or fetch lyrics again
