### ISSUE TITLE
[Feature]: List updates 

### ISSUE THREAD

**Issue by Grevellia123** [fast4x/RiMusic#2071]
### Description

I hope there will be a feature where you don't need to update via the website, but update via the application Example 
![Screenshot_2024-05-28-11-22-59-636_eu kanade tachiyomi yokai](https://github.com/fast4x/RiMusic/assets/134467260/b21dff26-1e1c-4771-a9a6-1698d0d67d80)

### Suggested Solution

Updating via the application is simpler than via the website

### Alternatives

Update via application

**Comment by fast4x** [comment]
Hello, it is not a question of simplicity but of permissions. 
The update with automatic installation is an operation not totally managed by the user. For this reason, and because F-Droid considers an incorrect action, you have two options.
Click on the link that goes to the site or on the download link that downloads the file to your device, you just need to click on it to start the installation.
