### ISSUE TITLE
Account login feature

### ISSUE THREAD

**Issue by debarjun2004** [fast4x/RiMusic#2160]
### Description

If possible, please add google login option, so the favourite songs and custom playlists don't get erased if uninstalled....... Thank you. 

### Suggested Solution

Like Spotify or something like that....

**Comment by JeePopuwu** [comment]
fast is not planning it since it says it breaks certain Rimusic parameters

**Comment by fast4x** [comment]
Sorry not planned

**Comment by Abilomp** [comment]
Please 🥺..
Plan it Fast4x brother please

**Comment by ikanakova** [comment]
It has been explained here several times (including in the [FAQ](https://github.com/fast4x/RiMusic/wiki/FAQs#why-there-are-no-plans-to-implement-google-or-youtube-login)) why there will NEVER (thank God!) be a Google or YouTube login and yet people feel the need to keep asking for it (#315 #344 #355 #640 #690 #791 #974 #1335) 🤦‍♀️
I don't think that by opening new and new FRs they'll convince anyone of that, when it's not only stupid because it compromises user privacy, but it's also dangerous because we'll draw Google's attention to RiMusic and RiMusic could end up like the Barinsta app and I really hope nobody wants that...

**Comment by Abilomp** [comment]
I agree with you.

**Comment by fast4x** [comment]
Started development of piped account and synchronization 🎉

**Comment by debarjun2004** [comment]
Hell yeah!!!
