### ISSUE TITLE
Sharing.

### ISSUE THREAD

**Issue by qqqqwwweeeerrrr** [fast4x/RiMusic#2175]
### Description

Sharing playlists links.
Shared playlists.

### Suggested Solution

Create blended playlists with friends.
Share personal playlists to friends.

**Comment by fast4x** [comment]
Can export and share all playlist, songs and queue.

**Comment by Beshardis** [comment]
I'm sorry! Most likely, he meant syncing playlists.

**Comment by aneesh1122** [comment]
> Can export and share all playlist, songs and queue.

1) he wants to have a playlist where multiple people can add or delete songs. Like a collaborative playlist.

2) he wants to share playlists with his friends using a link.

After the implementation of planned piped integration he will be able to do the 2nd part of the request.

The 1st one is impossible I think.

**Comment by Beshardis** [comment]
In general, to make some kind of system through sharing. Like making some kind of "friends" tab, where:
1 person makes a "backup", then passes it to another.
And already another person decides how to apply this backup: as a simple recovery system (as usual), or through the "upload friend data" button, where the listening history data and everything else will be in the "friends" tab!
everything is simple, even if the data (new playlists, etc.) of 1 person has been updated in order to transfer new data, it is enough to simply make a new backup and transfer it.

The main thing is to have a concept where if you add a friend's data, then this data simply cannot be edited and that's it!
I think that you can make playlists by the same analogy, but marked "general". People will transfer data to it, but edit it, let those who know the password be. But to be able to give separate permissions to people to add and delete. When adding those songs that already exist, they remain without being copied. And those that are new are just added.
If it's easier, then I create a playlist "general" and make my password there, then I give permission to any people without a password to add it. Then everyone who changed something throws off their backups of the "general" playlist and all the data adds up.

**Comment by fast4x** [comment]
It is very difficult to make and use. In the future can share playlist with piped.

**Comment by Beshardis** [comment]
Take your time, everything is ahead! You are the only one like this: "a brilliant mad developer", there are few people in the whole world!

**Comment by fast4x** [comment]
thanks a lot

**Comment by fast4x** [comment]
Started development of piped account and synchronization 🎉

**Comment by fast4x** [comment]
Implemented piped playlists syncronization, available from version 0.6.39
