### ISSUE TITLE
RiMusic flagged as Malware

### ISSUE THREAD

**Issue by Betelgeuse93** [fast4x/RiMusic#2287]
### Steps to reproduce the bug

. 

### Expected behavior

Not flagged as malware

### Actual behavior

Flagged as Evo-Gen

### RiMusic version

0.6.36

### Android version

Android 12.0.0.273

### Additional information

Hi, my Huawei P30 Lite marked the app as Malware, to be more precise is marked as Evo-Gen.

I download it from F-Droid

**Comment by ikanakova** [comment]
I trust F-Droid more than Huawei and I also have 0.6.36 installed on my Samsung and Eset, which I also have there, has no problem with it.

**Comment by ikanakova** [comment]
And the original apk goes through regular antimalware checks see https://apt.izzysoft.de/fdroid/index/apk/it.fast4x.rimusic/

**Comment by fast4x** [comment]
@Betelgeuse93 download apk ONLY from OFFICIAL place

**Comment by ThirdRandomCat** [comment]
Just confirming the same issue
adding screenshot (I hope, not sure if the screenshot is being uploaded) 

Only Fdroid version causes this alert, when downloaded both from IzzyOnDroid and directly from Github there are no issues 

Letting you know in case Fdroid version has been compromised 

I hope this helps 

![Uploading Screenshot_20240615_105820_com.huawei.appmarket.jpg…]()

**Comment by fast4x** [comment]
Your screenshot talk about Huawei app market....

**Comment by ThirdRandomCat** [comment]
Thanks for your reply

That is just the name of the image file 
I have not downloaded anything from HUAWEI repository

Additional information 

I clicked on your link to Fdroid on the app page and it takes me to an Italian site 

https://f-droid.org/it/packages/it.fast4x.rimusic/

The apk downloaded from there appears to be clean 

However, if I download the apk from the English version of Fdroid it gets flagged 
The same happens when installing using Fdroid app

I can attach the apk that is getting flagged for you to check if you want to 

I hope I can help

**Comment by ThirdRandomCat** [comment]
Correction

Even the apk downloaded from the Italian Fdroid site gets flagged

But Fdroid version is 0.6.36

Should it be updated maybe?

**Comment by fast4x** [comment]
Would be updated to next week, depend by F-Droid

**Comment by ThirdRandomCat** [comment]
Great!

I installed the latest version from github, so it's all good 

You are doing an amazing job

Thanks!

**Comment by fast4x** [comment]
Great

**Comment by ikanakova** [comment]
If you think the F-Droid version is compromised, don't post it here, because fast4x can't do anything about it, but on F-Droid: https://forum.f-droid.org/tag/malware / https://gitlab.com/fdroid/fdroiddata/-/issues
