### ISSUE TITLE
Release year fails to show up in album list

### ISSUE THREAD

**Issue by KeknanXD** [fast4x/RiMusic#2450]
### Steps to reproduce the bug

1. Go to albums menu
2. Click on a release (incl. those that previously failed to load)
3. Go back

### Expected behavior

The release shows up, songs are listed, and it gets sorted by release year when going back to the albums menu.

### Actual behavior

The release does show up, but the release year is removed and thus it gets pushed back at the bottom of the album list.

### Screenshots/Screen recordings

![Screenshot_20240624_141121](https://github.com/fast4x/RiMusic/assets/173551706/cf4b6209-0402-4a01-a4a6-ea6acc48e8ec)
![Screenshot_20240624_141130](https://github.com/fast4x/RiMusic/assets/173551706/18279edb-08a1-4b1e-8b33-2e1a0ea31c6b)
![Screenshot_20240624_141141](https://github.com/fast4x/RiMusic/assets/173551706/a64afe9a-1eaa-4108-b2a3-086734f8e47a)
![Screenshot_20240624_141148](https://github.com/fast4x/RiMusic/assets/173551706/61ae63dc-98a5-44dc-83e2-47cd290fa51b)

I've screenshotted a process example, that being Biocellulose by Current Value. Notice how the year gets removed and gets sent back to all the other releases without a year.

### RiMusic version

v0.6.40.1

### Android version

Android 12

### Additional information

I'd also like to add that Dream Noire by Current Value is still affected by the previous infamous "can't load release/album" issue, which is weird since every other release recovered from this. I may be the only one, or that issue is a little more specific. I'm not sure.

**Comment by wglee99** [comment]
I think this issue might have to do with the changed API response (by Youtube) which initially caused all the albums and playlists to disappear. I'm not seeing album release years either, however when I replaced the empty string with a placeholder value, the placeholder value shows up in place of the year, which leads me to believe that perhaps the issue is with the release years not being fetched from the API.

![image](https://github.com/fast4x/RiMusic/assets/79510234/559d2604-e239-42f8-991f-f399d73e41a2)

**Comment by NikunjKhangwal** [comment]
Definitely related to api changes. The disappeared albums during api changes are the ones not showing Year in my case. Other albums are showing it but that's because they were already cached.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.41
