### ISSUE TITLE
Custom download location of Downloaded songs

### ISSUE THREAD

**Issue by Brian2po** [fast4x/RiMusic#2647]
### Description

Save songs in external card because internal storage is near full. 

### Suggested Solution

Access custom folder(decided by user) to download songs in specified location.

**Comment by fast4x** [comment]
It is not possible because it would require special permits that would not allow publication on F-Droid, IzzyOnDeoid abd maybe also Accrescent.

**Comment by Radoom** [comment]
I would also appreciate if the downloads storage folder could be user-defined, including storage on SD-Card. Using old galaxy S4 with lineage (and another one even with the stock rom Lollipop as it works in a docking station only ever supported in that stock firmware) as audioplayers. Not sure, why would an app that demands read/write access to external SD-Card violate F-Droid rules? There's tons of e.g. file managers in there doing just that...

### Work-Around using `adb shell` or a terminal emulator on a rooted Android 5.0.1 device: 
**Let's bind-mount the desired folder on the external SD-Card instead of the folder on the internal storage where RiMusic stores the downloads.**

> Disclaimer: May be entirely unsafe, may break stuff, may lead to security risks and whatnot - I am not liable for any harm this may cause to you.

> Note: according to the [source](https://android.stackexchange.com/questions/203951/how-can-i-make-a-symlink-or-equivalent-inside-storage-emulated-0) this may only work / be necessary on Android 5 and/thru 7. Only tested 5.


On Android 5.0.1, RiMusic uses: `/storage/sdcard0/Android/data/it.fast4x.rimusic/files/downloads` but I want my stuff in `/storage/extSdCard/Music/RiMusic/`
Your paths may differ, depending on Android version I guess.

If you already have a lot of downloaded music in the original path, copy/move that stuff to where you want it first. For me, all subfolders and files under `.../downloads` went into `.../RiMusic`; afterwards, `.../downloads` is empty.

Then bind-mount like this:
````
adb shell
su -mm
mount -o bind /mnt/shell/emulated/0/Android/data/it.fast4x.rimusic/files/downloads /storage/extSdCard/Music/RiMusic/    
````
And afterwards, go into magisk manager > settings (cog wheel upper right corner in my old version) > scroll down to the "Superuser" section, tap on "Mount Namespace Mode" and select "Global Namespace".

Then let RiMusic download a fresh song. A new file should pop up somewhere in a subfolder of the new external `.../RiMusic`. Working :-) (for me)

**Comment by fast4x** [comment]
Nice workaround.

**Comment by Radoom** [comment]
Update to the Work-Around for Android 10 (I believe any from A9 and above may work like this from what I read):

> Disclaimer as in my original work-around-post above applies ;-)

> Credits: Not my knowledge at all. All based on [this excellent post](https://android.stackexchange.com/questions/217741/how-to-bind-mount-a-folder-inside-sdcard-with-correct-permissions/217936#217936)

One option might be to allow the phone to format the external SD as "Extended Storage", which sort of just adds it to the internal. Maybe by then re-installing RiMusic it goes to the external card in fact, including its data folder. Not tried as I didn't want to wipe my SD card. If it works, no bind-mounting is needed.

Option 2: bind-mount analogue to above, but different as the way storage is handled/protected is changed (as of A9 latest I understand, but maybe wrong). Anyhow, this worked for me on another S4 running LineageOS based on A10.

1. Had to make sure in developer options that the default USB connection mode is not "file transfer" or "charging" but "MTP" or "PTP" to get ADB to work with this phone/lineage version. May be different for you. 
2. Had to start `adb root` to make adbd restart as root before `adb shell` would allow to use `su -mm`
3. Path is different now; note that where it says `/write/` below, other options exist (`read` and `default`) but you must use `write`.
4. As in the original work-around post above, first moved the content of the original RiMusic `.../data/downloads/` folder (i.e. the subfolders) to the target folder on the SD card (`/Music/RiMusic` in my case); Note: Name of the SD-Card in my case is FF66-E3CB. Yours will be different, you should be able to find it in the output of the `mount` command in `adb shell` (or by several other ways...)

so, here's the commands:
````
adb root
adb shell
su -mm
mount -o bind /mnt/runtime/write/emulated/0/Android/data/it.fast4x.rimusic/files/downloads /mnt/runtime/write/FF66-E3CB/Music/RiMusic  
````
And afterwards, go into magisk manager > settings (cog wheel upper right corner in my version 25.x in this case) > scroll down to the "Superuser" section, tap on "Mount Namespace Mode" and select "Global Namespace".

**Comment by Radoom** [comment]
"Completed" as implemented (didn't see anything in latest release?), or as "won't ever do"?

**Comment by fast4x** [comment]
I can't implement it, sorry
