### ISSUE TITLE
Gradient does not work with thumbnail

### ISSUE THREAD

**Issue by twistios** [fast4x/RiMusic#2657]
### Steps to reproduce the bug

1. Enable background from thumbnail
2. Enable gradient
3. Play a song
4. Dis/Enable extend player
5. Enable Thumbnail

### Expected behavior

Gradient should also work with thumbnail

### Actual behavior

Gradient does not work, so it is hard to read.

### Screenshots/Screen recordings

https://github.com/fast4x/RiMusic/assets/54811436/8b3d0dee-cc2e-4b83-a97d-093de777e109

### RiMusic version

0.6.42

### Android version

14

### Additional information

Extended player can also not be used with thumbnail, it is always up instead of also down possible.

**Comment by aneesh1122** [comment]
> Extended player can also not be used with thumbnail, it is always up instead of also down possible

Expanded player is useless if you are using thumbnail for lyrics because words are limited to thumbnail so I disabled it for 'show thumbnail for lyrics'. one guy actually created an issue saying that the expanded player is not working so I disabled it completely for landscape mode and when "show thumbnail for lyrics" is enabled.

If you enable "show thumbnail" and disable "show thumbnail for lyrics" you can still have the expanded player.

**Comment by twistios** [comment]
It does not look useless to me. The thumbnail size is also increased.

https://github.com/fast4x/RiMusic/assets/54811436/5304dd31-3546-4247-b9f0-ad9cd9e87b15

**Comment by aneesh1122** [comment]
> It does not look useless to me

I made expanded player to have more space for lyrics. I just thought it won't do anything for users who are seeing lyrics inside the thumbnail

regarding the size of thumbnail, essential thumbnail doesn't have this issue. I had to add some padding to modern thumbnail because of the shadow.

**Comment by twistios** [comment]
But gradient should still work without expanded player or is this not possible?

**Comment by aneesh1122** [comment]
> But gradient should still work without expanded player or is this not possible?

I'm working on it right now.
