### ISSUE TITLE
Notification in HyperOS 

### ISSUE THREAD

**Issue by Claravallac** [fast4x/RiMusic#2741]
### Steps to reproduce the bug

I have a bug on Xiaomi's HyperOS (Android 14) where the favorite button stops working 

### Expected behavior

Songs should be favorited by pressing the button.

### Actual behavior

Nothing happens when you press the button.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/19f8ab48-c821-417f-bfe2-4452ec37787a

### RiMusic version

0.6.43

### Android version

Android 14

**Comment by lebgdeyoutube** [comment]
I confirm, when you click on the like from the notification, nothing is displayed. but the like is still put, it's just a display bug. on the other hand when we click again on the notification, we cannot remove the like . restart the application and the problem is corrected. Another problem is when you like from the application, it does not synchronize with the notification. but when you like from the notification, it is synchronized with the application
