### ISSUE TITLE
Quick option to change song quality 

### ISSUE THREAD

**Issue by Its-Tony** [fast4x/RiMusic#2742]
### Description

Additional quick option under seek bar for bitrate and audio quality.

### Suggested Solution

It should show song quality and bitrate in full screen player under seek bar like in image(edited). As in full screen we can't get song information, taping the quality/bitrate under seek bar can act as multipurpose option e.g. 1.single click to change audio quality.
2. Tap and hold to get additional info like Id,tag,bitrate,size,cached and Loudness etc.
![IMG_20240713_234150](https://github.com/user-attachments/assets/ce29231d-7ff3-457f-94b5-d396092d1e67)

**Comment by JeePopuwu** [comment]
yes we already have that in the download information

![Screenshot_2024-07-13-15-36-28-292_it fast4x rimusic](https://github.com/user-attachments/assets/908e839f-2b4e-4ecf-be22-3567a2dda967)

**Comment by aneesh1122** [comment]
> yes we already have that in the download information
> 
> ![Screenshot_2024-07-13-15-36-28-292_it fast4x rimusic](https://github.com/user-attachments/assets/908e839f-2b4e-4ecf-be22-3567a2dda967)
> 

Looks like everyone misunderstood him. When you disable "show thumbnail'" you don't have any way to see quality details.

@Its-Tony I can't put it there because 
1) the area is very small and people might end up touching something they didn't want to

2) I want the player to look clean.

I'll see what I can do

**Comment by Its-Tony** [comment]
Bhai, first of all thanks for that lyrics background option, now lyrics visibility is enhanced. In current version opacity slider is removed when you enabled full screen cover(only working in lyrics) so long tap on cover should show information.

**Comment by aneesh1122** [comment]
> so long tap on cover should show information

I'm planning to add something else there. 

For showing quality details maybe I'll add a row of text above the action bar.

**Comment by aneesh1122** [comment]
![WsaClient_OEzU2p9qlK](https://github.com/user-attachments/assets/3c2ca676-e598-4010-9620-5405d43d084b)

I did not add the option to click and change audio quality. I've kept only importation information here to not make it look messy.

**Comment by Its-Tony** [comment]
I think it will look good without gradient.If possible make them as in my screenshot(aesthetically that look better in my opinion) and add an option of touch and hold on that for 3 sec to show whole information.I think area is enough,It may be a problem for low display resolution phones,so make it optional.Leave option to change audio quality that is not used frequently.

**Comment by aneesh1122** [comment]
> I think it will look good without gradient

Even I think that and that's why it's optional. If you have transparent action bar this will also have a transparent background. If I make it transparent it will have visibility issues.

> If possible make them as in my screenshot(aesthetically that look better in my opinion)

You've put those things in between 2 components of the player. That is only making it look worse. I've put it at bottom and it doesn't interfere with anything there.

> add an option of touch and hold on that for 3 sec to show whole information

can't do that. sorry

> It may be a problem for low display resolution phones,so make it optional

Don't worry. It's optional.

**Comment by aneesh1122** [comment]
Is this what you wanted?

https://github.com/user-attachments/assets/d09528b6-47ae-4f45-9657-a0cf65516716
