### ISSUE TITLE
The song repeats even if you select the next button. 

### ISSUE THREAD

**Issue by YersonGD** [fast4x/RiMusic#3074]
### Steps to reproduce the bug

The song repeats even if you select the next button. 

### Expected behavior

The song repeats even if you select the next button. 

### Actual behavior

The song repeats even if you select the next button. 

### Screenshots/Screen recordings

The song repeats even if you select the next button. 

### Logs

The song repeats even if you select the next button. 

### RiMusic version

0.6.45.1

### Android version

Android 14

### Additional information

The song repeats even if you select the next button.

**Comment by twistios** [comment]
Please add more details. Because for me for example it is possible to switch to the next song via the "next song" button. Also you should consider updating to the latest version, as there was a bug that created for example problems with opening lyrics in 0.6.45.1 that got fix in 0.6.46 (or actually 0.6.45.1 custom version).

**Comment by KaiMaguro** [comment]
I am having the same issue. Only on my playlists. If i go into the public store, it seems to allow me to skip songs.
