### ISSUE TITLE
Player type

### ISSUE THREAD

**Issue by Alanpa1** [fast4x/RiMusic#3385]
### Description

When player type is Modern then we can slide up and down to change music ..so in next update please add option to disable and enable sliding one ..
And When player type is Essential the thumbnail of video didn't change corner roundness please fix..

### Suggested Solution

..

### Alternatives

..

### Additional Context

..

**Comment by aneesh1122** [comment]
why do you want to use modern player if you don't want to swipe to change songs? The whole reason why I added modern player is to see which song is up next while swiping the thumbnail.

btw the thumbnail size changing in essential player is a known bug and most probably it will be fixed in the next update.
