### ISSUE TITLE
An ideia 

### ISSUE THREAD

**Issue by Jcarz100204** [fast4x/RiMusic#3400]
### Description

Yall can make so i can put my all photos on mu playlists?

### Suggested Solution

I dont know much about programation but i think yall got code for chance the album cover so just put in on the playlist?

**Comment by fast4x** [comment]
Actually isn't possible

**Comment by faustaahmad** [comment]
Thumbnail are stored as url in the database (`.db`)
If you know then you know how to change each song's cover

I dont know if those cover will get update automatically, but I did encounter 1 case where a song (Arsonist by MSR) has no thumbnail 
Since "Hide" song wont reset/update the cover, so I need to look for a way to change the cover 
Turns out that the thumbnail value of that song is set to `null`

I changed my backup database with MiXplorer

**Comment by fast4x** [comment]
...or thumbnail URL isn't recognized...
