### ISSUE TITLE
[Feature]: Customizable slide behaviour

### ISSUE THREAD

**Issue by RIMOPA** [fast4x/RiMusic#3799]
### Description

When sliding a song to the right, it plays next. When sliding a song to the left, it's added to favorites. Except in playlists, where sliding left deletes them from the playlist. I don't know if there's other behaviour, but that's what I found. I would like to customize the behaviour of sliding songs left/right.

### Suggested Solution

Add options like "Play next", "Add to queue", "Delete", "Play", "Download", "Share", "Add to favorites"...

### Alternatives

You could also add customization for sliding albums, artists or full playlists.

**Comment by fast4x** [comment]
Not possible, can use Essential Player in settings

**Comment by ChickensioDev** [comment]
why not possible? just adding option in setting to choose "slight left behavior" and "slight right behavior" also can u disable slide left to delete in playlists? because i actually use the slide right gesture alot but sometimes when i scroll down it slide left instead and removes song from playlist

**Comment by fast4x** [comment]
there are a lot of other think with much priority....
