### ISSUE TITLE
Last position after opening an album, artist, or playlist

### ISSUE THREAD

**Issue by 6XChen** [fast4x/RiMusic#3840]
### Steps to reproduce the bug

1. Scroll down from the artist album page
2. Open any visible album
3. Press the back button
4. Then it will exit on the artist's home page

### Expected behavior

Not returning to the artist home page

### Actual behavior

When the back button is pressed, it returns to the artist's home page.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/85d518e3-3643-407c-99ef-9ef39271ff3e

### RiMusic version

0.6.54

### Android version

Android 14

**Comment by knighthat** [comment]
This is by design, the "back" button will return to previous screen.

All tabs on artist's page is considered a single page. Therefore, when you press "back" it exit the screen rather than taking you back to  the previous tab

Implementing "back" button for tabs is unnecessary since all tabs are visible, and it'll require you to press the "back" button multiple times to exit the page
