### ISSUE TITLE
settings tab not there

### ISSUE THREAD

**Issue by filixu** [fast4x/RiMusic#4005]
### Version of RiMusic

0.6.56.1

### Android version

14

### I've done these:

- [x] Uninstall old build before installing a new one
- [x] Checked opening issues about my similar problem

### Tell us how you trigger this bug

I updated RiMusic due to a download issue
The search and settings tab is unavailable 
![Screenshot_20241014_204935](https://github.com/user-attachments/assets/4abc262d-1470-49bb-8710-5af2d50dd55e)

### What was your expectation?

I expected to be able to check my settings, but it wasn't there.

**Comment by filixu** [comment]
If I'm dumb and it is actually there I apologize :(

**Comment by filixu** [comment]
I found a solution to the problem, but it's a little inconvenient, as it involves going to an artists page and pressing the 3 bars on the top right for the settings.

**Comment by SevenFactors** [comment]
I ran into this issue on version 0.6.56. Version 0.6.56.1 is not out yet on Accrescent.

The solution I found was to change the UI from ViMusic back to RiMusic. This solved the issue with the top-bar button and hamburger menu.  I don't know if the OP and those running version 0.6.56.1 could do the same to remedy their UI issues till the bug is fixed.

**Comment by filixu** [comment]
Changing the ui back to RiMusic helped fix my problem! thank you for helping with my issue!
