### ISSUE TITLE
Download don't work

### ISSUE THREAD

**Issue by Carlos353478** [fast4x/RiMusic#4012]
### Version of RiMusic

0.6.56.1

### Android version

10

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### What was your expectation?

I can't download some songs

### What more can you tell us? (Optional)

precisely the song that I cannot download sometimes does not play I have to press the song then change to another and again to the song that does not play and that is the only way to play it when I press the song that does not play a text appears in red that says media cannot be played

### Logs (Optional)

I can't i don't know how

**Comment by Carlos353478** [comment]
![Uploading Screenshot_20241015-215756~2.png…]()

**Comment by knighthat** [comment]
As far as I am concern, this is YT sending back phony response. You can verify that by start playing the song, chances are, it's unplayable.

**Comment by OrangeZXZ** [comment]
> As far as I am concern, this is YT sending back phony response. You can verify that by start playing the song, chances are, it's unplayable.

I noticed that RiMusic does not skip download errors, and that can block download queues.
I discovered this while trying to download a song without an active network.
The network was activated afterward, but I needed to terminate RiMusic from running in the background to start again.

I think this is also doing it when songs aren't available or if the song happened to not install, then you can't just install it back since it still tries to download it in the background. (needs to be terminated)
