### ISSUE TITLE
Disable scrolling text not working

### ISSUE THREAD

**Issue by foolishhh** [fast4x/RiMusic#4093]
### Version of RiMusic

0.6.56

### Android version

11

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. First time trying out RiMusic
2. tweaking with the settings
3. Clicked on interface in use
4. Switched to Vimusic
5. Tried to switch back to Rimusic but wouldn't work
6. cleared data
7. tweak with settings again
8. clicked on disable scrolling text
9. checked on long text
10. not working

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

https://github.com/user-attachments/assets/cd2dc09a-7331-41ed-a69b-02eeb77a943e

### What was your expectation?

i clicked on disable scrolling text and was expecting all of the long text to NOT scroll

**Comment by twistios** [comment]
RiMusic-mode is in general more maintained than ViMusic-mode. Most settings of ViMusic-mode can be set similar in RiMusic-mode. Please be aware that maybe ViMusic-mode will be removed at some point (also because it is mostly redundant to RiMusic-mode via settings).

How does the "switching to RiMusic-mode not working" show itself?

To your bug-report: It seems that I can confirm the problem of the scrolling not beeing stopped.

**Comment by twistios** [comment]
It seems that scrolling text gets disabled, but only Title and Artist in the player screen (full screen). It also seems that the scrolling at other places was implemented differently.

**Comment by twistios** [comment]
I am working on implementing this feature fully. Hopefully I don't forget something.

**Comment by fast4x** [comment]
Fixed by @twistios , available from version 0.6.58
