### ISSUE TITLE
This new update is just filled with bugs for real. Like I can't just play any song for the matter of record, before this update atleast some songs would play and some don't. But now it's just crashes, just click a song to play and crash. No matter how hard I try it won't play. Fix this please.

### ISSUE THREAD

**Issue by abhhii00** [fast4x/RiMusic#4121]
### Version of RiMusic

0.6.57.1

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on any song to play 
3. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Didn't expected it to play, and it does not.

### What more can you tell us? (Optional)

I just opened the app to play music and boom, no music is playing like literally no, it just crashes at the moment I click to play a song

**Comment by NullDott** [comment]
Same issue for me, only my downloaded songs worked, than I reinstalled to see if it helped and it didn't, everytime I'm trying to play a song a message saying "song cannot be played" appears.

**Comment by abhhii00** [comment]
I just hope they fix this, because rimusic is the only music streaming app I use and I don't want to shift to any other platforms.

**Comment by knighthat** [comment]
this is not because of our update, but YTM update, they're are on rampage

**Comment by abhhii00** [comment]
Hope it gets fixed.

**Comment by knighthat** [comment]
i just pushed #4122. Let's hope the owner accept it

**Comment by silvaf6** [comment]
You are being an Ass wipe.

The developers have no guilt about google updates. i experienced unresponsiveness before after a long time having the app on cache and restarting to play something. so what?

There are unlimited devices and different varients of Android. Can do a better job? i surely cannot.

give some monetary compensation, then you are on your right to make stupid complains, or go support the stupid youtube music ads.

This is a free "open source" app, if you know what it means, if not, educate yourself. maintained mostly by good will of unindependent devs.

Otherwise it would be on the playStore which is forbidden by google.

I'll leave this and won't response. I know it will be fixed unless the "owner" gets annoyed by your comments and abandons the project.

**Comment by aneesh1122** [comment]
Man..the f*cking entitlement of some people.

**Comment by i-dAnubis** [comment]
Dude, what if instead of having the creator fix the bug you go and fix your bank account and use YouTube Music and stop being such a pain in the *ss*

**Comment by silvaf6** [comment]
man. I apologize if i created a toxic environment, but better close the thread because the point was already taken and no further comments are realy necessary.

best regards everyone.peace

**Comment by abhhii00** [comment]
I don't know why, everyone just straight up hating on this, I just raised the issue I was facing in a hope that it will get fixed and I didn't have any intent of criticizing the developer or owner of this repo in any way or sense.

I'm Closing the issue thread.
Please do better in life. Gn.
