### ISSUE TITLE
Youtube connections seems not working

### ISSUE THREAD

**Issue by bernefr** [fast4x/RiMusic#4193]
### Version of RiMusic

0.6.58

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open Ri music
2. I use my Google credentials 
3. I restart application 
4. Try to play any music
5. I got a message "connexion needed to read this media"
![Screenshot_2024-10-26-11-36-33-940_it fast4x rimusic](https://github.com/user-attachments/assets/9872bea1-9017-469e-85ce-0372a3d48b85)
6. I try many Time to disconnect and reconnecte without success

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

I connect to my Google account but it seems not works

### What more can you tell us? (Optional)

Phones is Poco x4pro pro 5g with hyperos 1.0.8.0

**Comment by Renlou** [comment]
Same here. I've logged in through Settings > Misc > Connect YouTube.  Force quit through Apps settings, uninstall and reinstall. Restarted phone.
Nothing worked. 😕

**Comment by Potiron** [comment]
Same issue too

**Comment by Yurisouza30** [comment]
Same here

**Comment by fast4x** [comment]
Download latest version please.

**Comment by Potiron** [comment]
Nothing changed for me
It connect to youtube music,i Can see the channels,but no return or anything else to rimusic.
So im going back to it, restart and everything is as described on first post

**Comment by bernefr** [comment]
Hi, I've just installed the last release (0.6.58.1) and it seems ok, music is playing well as far as I tried it. And most surprising, I didn't connect to my youtube account.

**Comment by fast4x** [comment]
perfect

**Comment by lebgdeyoutube** [comment]
You can't connect to Google if you have several YouTube channels on the same account because if you launch the connection it opens a YouTube page instead of opening a YouTube music page.I found a temporary solution, once you are on Youtube type in the search bar "Google.fr". search for the Google Youtube channel and go to their description there is the link "google.fr" click on the link then once you are on Google search for YouTube music. and click on the YouTube music link and this will connect you to your first Youtube music account  but impossible to change account you can connect to only one the default one so it's a problem for those who have their main account not on the front line like me
