### ISSUE TITLE
Bug nello scorrimento delle pagine

### ISSUE THREAD

**Issue by CiccioDerole** [fast4x/RiMusic#4292]
### Version of RiMusic

0.6.58.1

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Apri Rimusic
2. Clicca su Artisti/Album
3. La pagina risulta già scorsa verso il basso

### Submit a video

https://github.com/user-attachments/assets/95b56421-495e-465d-8cc8-ae57ac8c7ba1

### What was your expectation?

La pagina dovrebbe mostrare i primi elementi dell'elenco senza essere già scorsa verso il basso

**Comment by fast4x** [comment]
Si, già segnalato oggi ci guardo, grazie.

**Comment by CiccioDerole** [comment]
Scusa ma avevo provato a cercare altri report di questo problema ma proprio non li ho trovati. Visto che esiste da varie versioni pensavo fossi il solo ad averlo😅

**Comment by knighthat** [comment]
Please excuse me for replying in English, I don't speak Italian.

The problem here is because `LazyVerticalGrid` renders items top down, as [spacer](https://github.com/fast4x/RiMusic/blob/d31be6618ee94da305403e43dd0fceceef1bcb4f/composeApp/src/androidMain/kotlin/it/fast4x/rimusic/ui/screens/home/HomeArtistsModern.kt#L237C1-L243C18) added last, the grid will scroll down to the bottom.

I have yet to find a solution to this.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.59
