### ISSUE TITLE
Custom Image for Playlists

### ISSUE THREAD

**Issue by PoPo-7** [fast4x/RiMusic#4327]
### Description

I would like to propose the addition of a feature that allows users to change the cover image of their playlists within the application. This enhancement could improve personalization and user engagement. Thank you for considering this suggestion. 
🌟

### Suggested Solution

It would be great to have a playlist option feature where we can easily change the image. An option to open File Explorer, that would let us pick any image we want.

**Comment by TimeRXperformer** [comment]
1. I support 
2. Displaying the original playlist image from YTM 
3. Has the option to edit the playlist image from the Rimusic application. 
4. If you press the sync button, there is an option for the playlist image to change to the original from YTM or not.
5. Options lock image playlist rather than change(edit from Rimusic application)

**Comment by Abhinavreddy-B** [comment]
Playlist custom thumbnail feature done in PR https://github.com/fast4x/RiMusic/pull/4411, lets wait till moderators to merge.

Though this PR doesnt contain the ability to get back the old thumbnail
