### ISSUE TITLE
[Feature]: Login

### ISSUE THREAD

**Issue by Teleposse** [fast4x/RiMusic#4372]
### Description

I think the ability to log in would be one of the most important features and changes.
You may have multiple devices with the same account.

### Suggested Solution

It would also make way for new functions that need this.
It would also solve problems of losing the device and therefore losing everything.(Or my problem,not being able to open the app)

### Additional Context

By the way, I think it's been more than a month and rimusic still hasn't opened.
That's why I wanted to know if you are trying to solve my problem, or if there is any way to contact you without having to open a post.
Thx for help or try It :)

**Comment by twistios** [comment]
A "RiMusic" account is not really possible because this would require a "RiMusic-Server" (what currently does not exist and probably would cost something to operate).
The app currently does support piped-login for sync of playlists (I'm not sure if it even works currently) and YTM.
Currently YTM is only used for logging in and there is no sync happening. But it seems that this is a plan for the future.

A way that already exists for backups is to use the database or playlist export. This can be used to restore all song/artist/playlist related information (but does not save downloaded files/the cache nor user settings, where user settings export is a planned feature).
