### ISSUE TITLE
If the "Keep minimized" option is open, continuously clicking the "forward" button opens the "mini player".

### ISSUE THREAD

**Issue by Figim** [fast4x/RiMusic#4786]
### Version of RiMusic

0.6.62.2

### Android version

12

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Play music
3. **Player type**: Modern
4. Turn on the "Keep minimized" option (settings)
5. Keep pressing the "forward" button in the main player. It's fun sometimes🙂
6. Main player changed to "mini player"

### Submit a video

https://github.com/user-attachments/assets/29c49649-1dde-4c6a-98fd-5c716d93b4f8

### What was your expectation?

If the "keep minimized" option is open, continuous clicking of the "forward" button does not open the mini player

### What more can you tell us? (Optional)

**Player type: Modern
Keep minimized : Active**

### Logs (Optional)

...

**Comment by twistios** [comment]
I can confirm this.

**Comment by twistios** [comment]
I have found the code section for what happens, if it gets mimimized by spamming the forward button.
When a normal transisition happens, then this is considered as `Player.MEDIA_ITEM_TRANSITION_REASON_SEEK`, but if you spam it, then it is `Player.MEDIA_ITEM_TRANSITION_REASON_PLAYLIST_CHANGED`.

**Comment by twistios** [comment]
I am currently checking the ExoPlayer implementation and the reason why it is considered as `MEDIA_ITEM_TRANSITION_REASON_PLAYLIST_CHANGED` is because an internal variable has the value of `DISCONTINUITY_REASON_REMOVE` which means (based on the documentation):
> Discontinuity caused by the removal of the current period from the Timeline.

Maybe I know what happens: The code that is called uses `setMediaItems` which (based on the documentation again)
> Clears the playlist and adds the specified media items.

This makes sense as the docs for `MEDIA_ITEM_TRANSITION_REASON_PLAYLIST_CHANGED` say that
> or when the playlist becomes non-empty after being empty.
