### ISSUE TITLE
Download Option 

### ISSUE THREAD

**Issue by Satya200405** [fast4x/RiMusic#4800]
### Description

When downloading the songs it will not coming in the internal storage it will help us to increase the viewers to your Rmusic company.

### Suggested Solution

Please give the option song downloading and it will come in internal storage 

### Alternatives

Please give the option download and will get the song in internal storage.

**Comment by fast4x** [comment]
Hi, RiMusic isn't a company...
Is not possible to save songs outside internal app reserved to app, because it require high level permissions in modern devices.
You can switch from cache to system cache, that not will be erased by system cleaner.
BTW songs are not exportable... RiMusic isn't a downloaded but only streaming player, modern, beautifull and many more features... :)
