### ISSUE TITLE
Duplicate artists

### ISSUE THREAD

**Issue by MedieroAF** [fast4x/RiMusic#4928]
### Version of RiMusic

0.6.64

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Have a song by X artist.
2. Click on artist name. It takes you to the artist's page.
3. Have different song, also by X artist.
4. Click on artist name.
5. Isn't counted as the same artist, although with the same name.

### Submit a video

https://github.com/user-attachments/assets/8b625fcf-d502-404e-bd6b-68df45826762

### What was your expectation?

Clicking on the artist name should always lead to the same page, regardless of the song.

### What more can you tell us? (Optional)

This only happens a very few times, but the example I attached as a video is one of those times.

It doesn't make the listening experience any worse, but it's kind of weird to have 3-4 duplicates of the same artist just because.

**Comment by twistios** [comment]
I assume that this problem is caused by the YT(M) API. Probably one of them is the "Topic" artist and the other one is the "channel" artist. Or maybe there is a different channel for YTM also.
In this sense it is not a bug but rather a missing feature (something like merge multiple artists into one).
