### ISSUE TITLE
Fast forward/backward or bookmark/tag

### ISSUE THREAD

**Issue by Tafim27** [fast4x/RiMusic#648]
### Description

I really feel the need for it. (Though rarely) Especially when I'm playing a favorite song of mine I feel like repeating a certain part of the song. Having a fast forward/backward would help with that more. 

### Suggested Solution

Though it might sometimes feel like a useful feature it is otherwise pretty useless ig. So I'm not sure if you should actually implement it or not. Though you could just implement it with enable/disable with making it disabled as default. But you would know better what to do after all I mean about implementing it or not. 
Thanks.

### Alternatives

Or maybe something like bookmark. Like how you "favorite" certain songs. Ability to "bookmark" (or idk what it should be called…maybe tag…anyway…) certain part of songs.

**Comment by faustaahmad** [comment]
It can be called Seek forward/backward instead of Fast forward (backward?)
Bookmark stuff is like Chapter in `.mkv` file, it maybe hard to implement even mpv-android doesnt have proper chapter seeking (Youtube does)

Alternative method was to use Synchronized Lyrics #208
But you cant have Lyrics popup, yeah...
\- Seek to next/previous verse
\- Seek forward/backward (custom miliseconds if possible)

**Comment by fast4x** [comment]
Implemented, increment/decrement 10s on long tap in forward/backward buttons
Available from version 0.6.22
