### ISSUE TITLE
Almost perfect 

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#653]
### Description

![Screenshot_20240210-081014](https://github.com/fast4x/RiMusic/assets/120176369/5116cd5d-72ab-4d73-b826-7f6993f710c8)

### Suggested Solution

![Screenshot_20240210-081014~2](https://github.com/fast4x/RiMusic/assets/120176369/75b58d14-cec2-4b7a-ad77-fcd0d87a5906)
Can u make this white bar rounded by releasing 6.21.1

### Alternatives

Please see issue #619 I added follow not subscribed button cause follow is the alternative of save icon

### Additional Context

@fast4x

**Comment by fast4x** [comment]
#619 Will be done soon.
I’ll roll the edges and give you a custom version.

**Comment by fast4x** [comment]
Thanks for "almost perfect" 😊

**Comment by OrangeZXZ** [comment]
I also think that it should be rounded but i also think that icons are too close to edges of the creen (this is good if you have a lot of icons but maybe do a limit of icons in the bottom and center them a bit

I also noticed that the queue has the bar (it shouldn't had it because you cant pull it up) and the bars are a bit tiny

**Comment by fast4x** [comment]
Icons have a max number of 6

**Comment by Logan7899** [comment]
> Icons have a max number of 6

No i mean to replace arrow with sleep timer

**Comment by fast4x** [comment]
Yes It make sense

**Comment by fast4x** [comment]
Implemented, available from version 0.6.22
