### ISSUE TITLE
Make only full screen mode lyrics clickable if possible

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#799]
### Description

When _toggle lyrics_ feature is enabled it becomes a habit to click on the thumbnail to toggle lyrics. So on that occasion if the lyrics is **clickable on the thumbnail** then it's hard to toggle.

Actually now that I checked it's a problem only when the thumbnail is medium/small sized. For big/biggest thumbnail it's not really much of a problem.

### Suggested Solution

1. Make only full screen mode lyrics clickable.
or
2. Slightly decrease thumbnail lyrics size.
or
3. Create an option so that we can chose if we want lyrics to be aligned on the right/middle/left.

I'd personally prefer the first solution. But since I have already been able to come up with 3 there might be more. But again this is not really that big of a problem so you can reject this suggestion if it's difficult.

**Comment by fast4x** [comment]
Ok

**Comment by Quinxxxx** [comment]
Would you be able to provide 2 toggles at the top with one being to show the normal player (call it song or sum) and the other called lyrics (shows you a full screen lyric page with synchronized lyrics being the default if available). 
![IMG_20240222_111405](https://github.com/fast4x/RiMusic/assets/88912716/50dd5204-79ea-4457-9de1-ffef6faded9c)

Kinda similar to what YTM does but replace the "video" button with lyrics since rimusic doesn't allow watching the music videos.
![Screenshot_2024-02-22-11-14-38-47_801c3494cc30bc6d615367769f98046d](https://github.com/fast4x/RiMusic/assets/88912716/a6eeb847-b1a1-4a53-a8b8-d0cd8c76b052)

**Comment by OrangeZXZ** [comment]
> Would you be able to provide 2 toggles at the top with one being to show the normal player (call it song or sum) and the other called lyrics (shows you a full screen lyric page with synchronized lyrics being the default if available). 
> ![IMG_20240222_111405](https://github.com/fast4x/RiMusic/assets/88912716/50dd5204-79ea-4457-9de1-ffef6faded9c)
> 
> Kinda similar to what YTM does but replace the "video" button with lyrics since rimusic doesn't allow watching the music videos.
> ![Screenshot_2024-02-22-11-14-38-47_801c3494cc30bc6d615367769f98046d](https://github.com/fast4x/RiMusic/assets/88912716/a6eeb847-b1a1-4a53-a8b8-d0cd8c76b052)
> 

I think à way to do that and keep a new look without copying is to put 2 icons (Lirics and Vizualiser) in the 2 bottom corners I think it would look nice but needs to be tested

**Comment by OrangeZXZ** [comment]
> hi @fast4x sorry I haven't been here for last few months… but why is this feature not available anymore? no fullscreen lyrics anymore and "jump to lyrics" is possible in the thumbnail which the feature i want but only in full screen mode… while minimized thumbnail its troublesome… please consider this issue again 

It was removed (I forgot why), and it was replaced by a big mode where the UI moves to make space for lyrics.
