### ISSUE TITLE
Play button on full screen lyrics

### ISSUE THREAD

**Issue by AnyoneMouse** [fast4x/RiMusic#889]
### Description

Show forward, backward and play button on full screen lyrics. Especially the play button. Other two buttons aren't that necessary there I think.

### Suggested Solution

Something like this:
![InCollage_20240302_003505513](https://github.com/fast4x/RiMusic/assets/85461823/d4f7d5a9-3862-4cf0-bf7f-481eb7d9ff77)

### Additional Context

Also unlike #677 I think song timeline/progress bar is not needed at all on full screen lyrics. But that's totally just my personal opinion.

**Comment by fast4x** [comment]
Wow thanks for the compliments. 
The time i spend developing is very similar to the previous months. The thing that is constantly changing are the priorities to be developed that i analyze carefully and strategically to make the app better known.

The release time i think i keep them to a week for some time. The reason is that i use an agile development process like SCRUM that allows a quick approach to the analysis, development and release of functionality or fix.

I hope I never have to abandon the project, because I really like it, it gives me a lot of satisfaction especially with users like you and others.
I try to do a good job compatible with my working and personal life.

I thank you again.

**Comment by sayyid5416** [comment]
I just found out about this app a few days ago, and I switched from YT music _(revanced 😉)_ instantly. I love this app, and I agree with every word of @AnyoneMouse about @fast4x. One of the best things about this app is its developer. Thanks a lot for this app and your hard work, I really appreciate it.

**Comment by fast4x** [comment]
Thanks, I'm honored
