### ISSUE TITLE
Dynamic theme

### ISSUE THREAD

**Issue by Logan7899** [fast4x/RiMusic#975]
### Steps to reproduce the bug

1. Go to UI option in settings
2. Select dynamic theme

### Expected behavior

The theme should not be pitchblack
![Screenshot_20240309_041646](https://github.com/fast4x/RiMusic/assets/120176369/5fa913ca-85b1-440d-a2e2-59662821dc52)

### Actual behavior

It is pitch black

### RiMusic version

0.6.25

### Android version

Android 14

**Comment by fast4x** [comment]
Do you have changed theme mode to light or system?

**Comment by Logan7899** [comment]
I changed it to system
![Screenshot_20240309_042519](https://github.com/fast4x/RiMusic/assets/120176369/d962b43a-4c1b-4ad9-9e71-239abfc70dcc)

**Comment by dAtA-TRoN** [comment]
@fast4x duplicate #964

**Comment by Logan7899** [comment]
Lol I didn't understand why he wanted pitch black in dynamic support. What about other devices which do notbhave amoked display and earlier dynamic looks good but here it is missing a many things

**Comment by senolfndk** [comment]
Why did you change the dynamic theme?![Screenshot_20240309-022319.jpg](https://github.com/fast4x/RiMusic/assets/52818836/dbf350a9-634b-48ca-abbf-0d9a1737cb6a)

**Comment by senolfndk** [comment]
Apply dynamic theme to progress bar![Screenshot_20240309-023019_Gramophone.jpg](https://github.com/fast4x/RiMusic/assets/52818836/34f43064-448c-4d99-98c5-6b08dcfef93e)

**Comment by fast4x** [comment]
Implemented Pitch Black theme mode, available from version 0.6.26

**Comment by fast4x** [comment]
Now dynamic is original and pitch black new black night

**Comment by OrangeZXZ** [comment]
> Now dynamic is original and pitch black new black night

That means we are going to have Dynamic and Dynamic Black? Because i really like how it is right now

If so you can add it here as "Dynamic Amoled" or "Dynamic Black":
![Screenshot_20240309_015234.jpg](https://github.com/fast4x/RiMusic/assets/104271365/d631b850-c52e-4a25-8fe7-91e26252e318)

But a better thing to do is add a Amoled option in the colors that way if we chese a theme only background colors ate changed to black:
![Screenshot_20240309_015238.jpg](https://github.com/fast4x/RiMusic/assets/104271365/e02d81a2-3806-4fa5-8dc1-454cbed154b1)

If you do that there is also this bug that makes the UI too flat and hard to see buttons and bar:
![Screenshot_20240309_015248.jpg](https://github.com/fast4x/RiMusic/assets/104271365/720b21c5-c772-43fa-bd5c-d06cd91ba046)

**Comment by fast4x** [comment]
i have restored original dynamic and added Pitch Black wich is identical to dynamic but with BLACK BLACK NLACK background. Why would be AMOLED and not PITCH BLACK?

**Comment by dAtA-TRoN** [comment]
> i have restored original dynamic and added Pitch Black wich is identical to dynamic but with BLACK BLACK NLACK background. Why would be AMOLED and not PITCH BLACK?

Thank you very much 🙏🏼!

**Comment by Vishcot** [comment]
> i have restored original dynamic and added Pitch Black wich is identical to dynamic but with BLACK BLACK NLACK background. Why would be AMOLED and not PITCH BLACK?

i want to suggest something i feel would be more beautiful, 
A theme that would be amoled enabled, but when we open player, it would showcase the original dynamic theme in background, that means amoled everywhere but, original dynamic theme colors inside player and queue! 

how would it look in your opinion? 

ps: i took this reference from Spotify and YouTube Music.

**Comment by fast4x** [comment]
Challenging ahahahah

**Comment by Vishcot** [comment]
> Challenging ahahahah

no issues, its upto you! if anyhow would be possible,  would love to see this and if not, still cool!
