### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by pst007x** [fast4x/RiMusic#993]
### Steps to reproduce the bug

1. Select download
2. Music shows in downloaded tab
3. No music downloaded to device 

### Expected behavior

Song to download 

### Actual behavior

No download found on device.

### RiMusic version

0.6.23

### Android version

13

**Comment by Nikks84** [comment]
Update the latest version

**Comment by sayyid5416** [comment]
It's not a bug. It's the expected behavior.

This app is not a music downloader app, it's more of a music streaming app like spotify or youtube music but with many additional features. Downloading works similar to spotify or youtube music. 

You can play the downloaded songs using this app from Library when offline.

**Comment by pst007x** [comment]
> It's not a bug. It's the expected behavior.
> 
> This app is not a music downloader app, it's more of a music streaming app like spotify or youtube music but with many additional features. Downloading works similar to spotify or youtube music.
> 
> You can play the downloaded songs using this app from Library when offline.

My misunderstanding. Thanks for the info.
